set fish_greeting

# Aliases

alias cal 'cal -m'
alias pdflatex 'pdflatex -interaction nonstopmode'
alias xclip 'xclip -selection c'
alias emacsc 'emacsclient --no-wait'
alias exti 'exit'
alias halt 'sudo shutdown -h now'
alias reboot 'sudo shutdown -r now'

alias fsk 'cd ~/uni/fsk-timi-2024'
alias fsko 'cd ~/uni/fsk-timi-2023'
alias aec 'cd ~/uni/serve/git-icfp-aec/events/2023'
alias aesop 'cd ~/uni/aesop/work'
alias aesopm 'cd ~/uni/aesop/master'
alias aesopfc 'cd ~/uni/aesop/forward-code'
alias aesopfd 'cd ~/uni/aesop/forward-design'
alias tcs 'cd ~/uni/tcs-www'
alias lehre 'cd ~/uni/tcs-www/lehre/ss-2024/'
alias meta-book 'cd ~/uni/meta-book'
alias book 'cd ~/uni/proof-assistants-book/tex/03_inductive_types_and_recursive_functions/'
alias website 'cd ~/prog/blog'
alias mathlib 'cd ~/uni/mathlib4/work'
alias mathlibm 'cd ~/uni/mathlib4/master'
alias sv 'cd ~/uni/sv'
alias krepp 'cd ~/uni/krepp'
alias uni 'cd ~/uni/'
alias leanm 'cd ~/uni/lean4/master'
alias leanw 'cd ~/uni/lean4/work'
alias std 'cd ~/uni/std4/work'
alias stdm 'cd ~/uni/std4/main'
alias talk 'cd ~/uni/talk'
alias regensburg 'cd ~/uni/talk/2023-09-regensburg'
alias aeneas 'cd ~/uni/aeneas/work'
alias aeneasm 'cd ~/uni/aeneas/main'
alias seminar 'cd ~/uni/sf-seminar/'
