alias beb="bundle exec bash"
alias cal="cal -m"
alias dox="xinit &>> ~/.xinit.log &"
alias emerge-update="sudo emerge --update --with-bdeps=y --newuse --deep world && sudo emerge --depclean && sudo revdep-rebuild"
alias halt="/sbin/halt"
alias pdflatex="pdflatex -interaction nonstopmode"
alias reboot="/sbin/reboot"
alias suspend="sudo /usr/sbin/pm-suspend"
alias time="time -p"
alias xclip="xclip -selection c"
alias mailx="mkdir -p /tmp/mailx && TMPDIR=/tmp/mailx mailx"
