alias mpva="mpv --no-video"
alias beb="bundle exec bash"
alias cal="cal -m"
alias dox="xinit &>> ~/.xinit.log &"
alias pdflatex="pdflatex -interaction nonstopmode"
#alias time="time -p"
alias xclip="xclip -selection c"
alias mailx="mkdir -p /tmp/mailx && TMPDIR=/tmp/mailx mailx"

alias halt="bup up && /sbin/halt"
alias reboot="bup up && /sbin/reboot"
alias suspend="sudo /usr/sbin/pm-suspend"

alias tournaman="wine ~/'.wine/drive_c/Program Files (x86)/Tournaman/Tournaman.exe'"
alias vgaon="xrandr --output VGA1 --auto --primary --output LVDS1 --off && xrandr --output LVDS1 --auto"
alias vgaoff="xrandr --output VGA1 --off"
