#!/bin/bash

# Logging
echo "====="
echo "Starting on $(date)"
echo "====="

# DBus
if command -v dbus-launch >/dev/null && test -z "${DBUS_SESSION_BUS_ADDRESS}"; then
   eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# Monitor setup for Desktop PC
which-machine
if [ "$?" -eq 0 ]; then
  xrandr --output DP-0 --primary --mode 2560x1440 --rate 144 --output HDMI-0 --mode 1920x1080 --rate 60 --left-of DP-0
fi

# Daemons
which xbindkeys &>/dev/null
[ $? -eq 0 ] && xbindkeys -f "/home/jannis/.config/xbindkeys/rc"

which redshift &>/dev/null
[ $? -eq 0 ] && redshift &

which picom &>/dev/null
[ $? -eq 0 ] && picom --daemon

gentoo-pipewire-launcher &

# Background
xsetroot -solid black -cursor_name left_ptr
feh --bg-max --randomize --no-fehbg -r '/home/jannis/.nocdp/wallpaper'

which xbacklight &>/dev/null
[ $? -eq 0 ] && xbacklight -set 60

# No screen blanking, thank you
xset -dpms
xset s off

# Extra keys
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

exec i3
