#!/usr/bin/env bash

REPO="$HOME/.emacs.d"
COMMIT="b63b209dd30a445210726ddb3c33981122caff38"

if [ ! -d "$REPO" ]; then
  git clone https://github.com/hlissner/doom-emacs "$REPO"
fi

git -C "$REPO" fetch origin && \
  git -C "$REPO" checkout "$COMMIT"
