#!/usr/bin/env bash

REPO="$HOME/.emacs.d"
COMMIT="559229c250620b83b47593e78f77b4351ea2de9a"

if [ ! -d "$REPO" ]; then
  git clone https://github.com/hlissner/doom-emacs "$REPO"
fi

git -C "$REPO" fetch origin && \
  git -C "$REPO" checkout "$COMMIT"
