#!/usr/bin/env bash

REPO="$HOME/.emacs.d"
COMMIT="4e105a95af9c4c7e86471e5566eb7a5ff776ec92"

if [ ! -d "$REPO" ]; then
  git clone https://github.com/hlissner/doom-emacs "$REPO"
fi

git -C "$REPO" fetch origin && \
  git -C "$REPO" checkout "$COMMIT"
